---
# Handlers used by the IT role

- name: apt update
  apt:
    update_cache: yes
  listen: apt update

- name: restart ssh
  service:
    name: ssh
    state: restarted
  listen: restart ssh

- name: apply netplan
  command: netplan apply
  become: true
  listen: apply netplan
